# Generated by Django 5.1 on 2024-08-31 14:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Podaj datę: ')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia: ')),
                ('end_time', models.TimeField(verbose_name='Godzina zakoczenia: ')),
                ('desc', models.CharField(blank=True, max_length=150, verbose_name='Opis: ')),
                ('type', models.IntegerField(choices=[(1, 'Zwykły czas pracy'), (2, 'Nadgodziny'), (3, 'Urlop'), (4, 'Zwolnienie lekarskie'), (5, 'Opieka nad dzieckiem')], default=1, verbose_name='Wybierz rodzaj pracy:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
