# Generated by Django 5.1 on 2024-09-02 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_row_end_time_alter_row_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='overtime_hours',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Całkowity czas nadgodzin'),
        ),
        migrations.AddField(
            model_name='row',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Całkowity czas pracy'),
        ),
        migrations.AlterField(
            model_name='row',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Podaj datę'),
        ),
        migrations.AlterField(
            model_name='row',
            name='desc',
            field=models.CharField(blank=True, max_length=150, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='row',
            name='end_time',
            field=models.TimeField(default='01:00', verbose_name='Godzina zakoczenia'),
        ),
        migrations.AlterField(
            model_name='row',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='Godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='row',
            name='type',
            field=models.IntegerField(choices=[(1, 'Zwykły czas pracy'), (2, 'Nadgodziny'), (3, 'Urlop'), (4, 'Zwolnienie lekarskie'), (5, 'Opieka nad dzieckiem'), (6, 'Praca zdalna')], default=1, verbose_name='Wybierz rodzaj pracy'),
        ),
    ]
